export const ru_aboutdata = {
  title: "Lorem ipsum",
  motto: "Nostrum, ab quas beatae facilis Lorem",
  section_a:
    "Dignissimos tempore itaque, dolor suscipit aspernatur vero libero",
  section_b:
    "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus corrupti beatae nemo repellendus neque, doloribus quod! Illum laboriosam neque labore voluptate quisquam atque voluptas repudiandae cumque accusamus consectetur possimus magnam similique libero et soluta sunt nisi voluptatem reiciendis, dolorum esse ducimus odit perspiciatis. Voluptates sunt aspernatur consequatur itaque fuga quisquam facilis? Omnis obcaecati doloremque voluptate accusamus asperiores, veritatis earum illo repellat odio eligendi tenetur tempore dolorem commodi dolore, ex nostrum doloribus minus accusantium rem? Eaque doloribus facere quasi aliquam modi. Ducimus vitae mollitia recusandae? Quos impedit neque reprehenderit explicabo. Cumque, vitae harum doloremque enim veniam dolorum, nisi, amet aliquam odit quae distinctio. Quisquam quia deleniti sunt. Suscipit asperiores, repellendus pariatur provident quaerat odio, eius quia vitae officiis ipsum velit praesentium neque esse itaque, dicta fugit dolor architecto eveniet est? Harum magni molestiae modi repellendus ducimus minima quasi, quo rem doloremque quod, similique sint laborum ea aperiam in quam eaque. Dolorum sequi aperiam obcaecati enim magnam impedit, natus debitis harum, quibusdam placeat facere! Labore enim animi, suscipit dolorem maxime aliquid optio cumque eaque a atque libero. Facere ullam harum tempora officia reprehenderit! Nobis neque vel illum perspiciatis illo error suscipit est cumque. Ipsum neque, eius enim perferendis adipisci incidunt tempore minus?",
  section_c:
    "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Mollitia fuga sequi necessitatibus dignissimos ad consequatur eaque, officia, iusto, similique deserunt dolore! Doloribus deserunt accusantium veniam nostrum. Quam eius dolores accusantium nam omnis, maiores reiciendis enim magnam quisquam ullam? Eligendi veritatis eius laboriosam porro natus, perspiciatis ratione ab corrupti, numquam ipsum ut officia a quis, quidem cumque totam tenetur illo delectus? Necessitatibus aliquam voluptates possimus. Labore quia modi voluptate sint nulla. Cumque, laboriosam consequatur? Consectetur, voluptas laboriosam cumque illum quia ipsa enim magni assumenda commodi impedit? Culpa totam asperiores corporis, quod pariatur sequi deserunt obcaecati doloribus, officia nobis, numquam reiciendis! Minima!",
};
